In [ ]:
#Referensi: https://www.linkedin.com/pulse/how-scrape-google-play-reviews-4-simple-steps-using-python-kundi/
# instal module untuk menambang data dari google play store
!pip install google-play-scraper

Collecting google-play-scraper
  Downloading google-play-scraper-1.0.3.tar.gz (52 kB)
     |████████████████████████████████| 52 kB 995 kB/s
Building wheels for collected packages: google-play-scraper
  Building wheel for google-play-scraper (setup.py) ... done
  Created wheel for google-play-scraper: filename=google_play_scraper-1.0.3-py3-none-any.whl size=24394 sha256=3097f77a48a7c42520ff2b2fa08160b522fcb7c4c6a169eaf510f3c43a79a761
  Stored in directory: /root/.cache/pip/wheels/81/37/0b/4a14be55b449a048cd93d79930b1a980dee7896480defa1923
Successfully built google-play-scraper
Installing collected packages: google-play-scraper
Successfully installed google-play-scraper-1.0.3

In [ ]:
# import module untuk mendapatakn data play store
from google_play_scraper import app

import pandas as pd

import numpy as np

In [ ]:
#Scraping data reviewer Pengguna Aplikasi Peduli Lindungi

from google_play_scraper import Sort, reviews

result, continuation_token = reviews(
    'com.telkom.tracencare',
    lang='id', # defaults to 'id' agar bahasa yang tersimpan pada penambangan data yaitu bahasa indonesia
    country='id', # defaults to 'id' agar hanya memfilter data review dari negara indonesia
    sort=Sort.MOST_RELEVANT, # defaults to Sort.MOST_RELEVANT untuk data yang cocok atau Sort.NEWEST untuk data yang terbaru reviews
    count=1000, # defaults to 100
    filter_score_with=None # defaults to None(agar mendapatkan semua score) gunakan 1 atau 2 atau 3 atau 4 atau 5 untuk memilih score bintang di playstore
)

In [ ]:
df_busu = pd.DataFrame(np.array(result),columns=['review'])

df_busu = df_busu.join(pd.DataFrame(df_busu.pop('review').tolist()))

df_busu.head()

,reviewId,userName,userImage,content,score,thumbsUpCount,reviewCreatedVersion,at,replyContent,repliedAt
0,gp:AOqpTOGvCvpo4MjfWTfwwP_tfGgfaalwcWL_d3KJxt7...,Rafazi_Fauzi Rahmat,https://play-lh.googleusercontent.com/a/AATXAJ...,"Aplikasi Cukup Membantu, sudah jauh lebih baik...",3,415,4.3.0,2022-04-09 15:55:11,"Halo,\n\nTerima kasih atas dukungan Anda.\nKam...",2022-04-09 17:38:06
1,gp:AOqpTOHRCgmZFL_MVIk8Y2LFJJj-M9Hn4qqSqS2eAda...,Gerry Fernandinho,https://play-lh.googleusercontent.com/a-/AOh14...,Aplikasi yang sangat membantu saya untuk check...,5,651,4.4,2022-04-11 09:59:21,"Halo Kak,\n\nTerima kasih atas dukungan Anda.\...",2022-04-11 12:53:04
2,gp:AOqpTOEkduYukqTDfPm4oJL77hSW2MWrCbARQ1pJmdc...,muhammad khafifudin,https://play-lh.googleusercontent.com/a-/AOh14...,"Android sudah versi 9, katanya minimal versi 7...",1,277,4.4.1,2022-04-15 08:11:12,"Halo,\nPastikan Anda sudah melakukan registras...",2022-04-15 11:05:48
3,gp:AOqpTOEbPiTbxOJzX4Z8lHZBHnYEwSGAeJb5QoExXuT...,Hamazim Afifudin,https://play-lh.googleusercontent.com/a/AATXAJ...,"Kanapa sudah upgrade, tapi makin susah, saya c...",2,188,4.4.1,2022-04-20 12:42:26,"Halo,\n\nMohon maaf atas ketidaknyamanan Anda....",2022-04-20 22:04:42
4,gp:AOqpTOFBx4aSG75wYJmJ2A9Q4lvlCNZ90_seF0Lrky9...,Taufik Hidayat,https://play-lh.googleusercontent.com/a/AATXAJ...,"Kurang user friendly, contoh sertifikat yg saa...",3,35,4.4,2022-04-12 13:29:19,"Halo Ka,\n\nKami mohon maaf atas ketidaknyaman...",2022-04-12 18:42:33

In [ ]:
len(df_busu.index) # menhitung jumlah data yang kita dapat

1000

In [ ]:
df_busu[['userName', 'score','at', 'content']].head()  #mengambil hanya userName, rating, date-time, dan reviews

,userName,score,at,content
0,Rafazi_Fauzi Rahmat,3,2022-04-09 15:55:11,"Aplikasi Cukup Membantu, sudah jauh lebih baik..."
1,Gerry Fernandinho,5,2022-04-11 09:59:21,Aplikasi yang sangat membantu saya untuk check...
2,muhammad khafifudin,1,2022-04-15 08:11:12,"Android sudah versi 9, katanya minimal versi 7..."
3,Hamazim Afifudin,2,2022-04-20 12:42:26,"Kanapa sudah upgrade, tapi makin susah, saya c..."
4,Taufik Hidayat,3,2022-04-12 13:29:19,"Kurang user friendly, contoh sertifikat yg saa..."

In [ ]:
new_df = df_busu[['userName', 'score','at', 'content']]
sorted_df = new_df.sort_values(by='at', ascending=False) #Sort by Newst, change to True if you want to sort by Oldest.
sorted_df.head()

,userName,score,at,content
223,Christine Napitupulu,2,2022-04-23 12:19:40,Saya mau download sertifikat vaksin perjalanan...
51,Alle Jandro,2,2022-04-23 11:20:59,"Warna masih merah, padahal sudah vaksin sampai..."
339,Sinta Aliyudin,1,2022-04-23 07:20:02,Saya sudah vaksin ke 3 tapi sertifikat tidak a...
258,Suci Anti,2,2022-04-23 07:12:08,Tolong diperbaikiii lagi please....! Gak semua...
129,Lina Karlina,1,2022-04-23 06:41:18,"Tolong yg buat aplikasinya perbaiki lagi, masa..."

In [ ]:
my_df = sorted_df[['userName', 'score','at', 'content']] #get userName, rating, date-time, and reviews only

In [ ]:
my_df.head()

,userName,score,at,content
223,Christine Napitupulu,2,2022-04-23 12:19:40,Saya mau download sertifikat vaksin perjalanan...
51,Alle Jandro,2,2022-04-23 11:20:59,"Warna masih merah, padahal sudah vaksin sampai..."
339,Sinta Aliyudin,1,2022-04-23 07:20:02,Saya sudah vaksin ke 3 tapi sertifikat tidak a...
258,Suci Anti,2,2022-04-23 07:12:08,Tolong diperbaikiii lagi please....! Gak semua...
129,Lina Karlina,1,2022-04-23 06:41:18,"Tolong yg buat aplikasinya perbaiki lagi, masa..."

In [ ]:
my_df.to_csv('scrapped_data.csv',index = False)